env:
  global:
  - COMPONENT=front
  - TOOLS_DIR=$HOME/tools
  - PATH=$TOOLS_DIR/bin:$PATH
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: AAAAB3NzaC1yc2EAAAADAQABAAABAQDfa3jRvePHwuvxfFRTgnbMRmKsHekLUuk2oaSBJS2/WKARDeHOqMpy65p//m9ZFnDxZCqVAbdwMlAPn0vXhsqQXUOE1AeAdKPjkbY/5p4KeO10KTiyqJkc8D+qWASTZM43SS4lHYIWFAk0zHILYUvS8yryUAxQHx0XUMJwJnmM5ulAbPdDulWhQBo3t4X6VKdx2YGZzcy7Qzt8BjTmQAAsH7Qp+0yhxr0O8AswAua/tUac46/gfZ9ddk4yfT+GpaElJFjs3uWQ+JuN1u02zdbSfBmQCnHiu5z3iWUksA0GXA8xbmhWB6BvMJcS6QhlIH/Qb1xh2eJp0gYiWD2M0+Ut
language: bash
sudo: required
before_deploy:
- sudo pip install 'requests[security]' awscli
- "$TRAVIS_BUILD_DIR/tools/install_packages.sh $TOOLS_DIR"
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/tools && ./deploy.sh
